### ISSUE TITLE
About: 'before define the value of a variable, try to change the shape of the variable'

### ISSUE THREAD

**Issue by jianhui1998** [apozas/fullnn#3]
#### Self-Diagnosis

- [x] I have reviewed the documentation.
- [x] I have reviewed the Wiki.
- [x] I have tried to use the latest version of Picos, Numpy and other required interface.
- [x] I have searched the issues for an answer to my question. 
- [x] I have searched the web for an answer to my question.

#### Environment(for bug reports)

- [x] Operating System:MacOs(12.0.1)
- [x] IDE version:VS code 1.65.1 (Universal)
- [x] Python version:Python 3.9.7

#### My configuration/Related code

```python
import numpy as np
import picos as pic

probabilities = pic.RealVariable('pinf',
                                   shape=3456,
                                   lower=0)
pinf = np.reshape(probabilities, (2,4,4,2,2,3,3,3))
```

#### Steps to Reproduce the Issue

1. The issue arise in Deriving (again) Equation 6, function:set_problem_C_NS() and a similar section that follows.

2. By picos.RealVariable() introduce a variable (probabilities) which value is None.
3. With numpy.reshape() on the variable, and report a Bug: picos.valuable.NotValued: Mutable pinf is not valued.

#### Current Result

1. picos.valuable.NotValued: Mutable pinf is not valued.
2. And you cannot reshape a variable which value is None.

#### Expected Result

Please check if you forgot to define the value of the probabilities, or if I got it wrong, please let me know.

**Comment by apozas** [comment]
Hello,

Thanks for the tip. This seems to be caused by newer version of `picos`. In [version 2.3](https://picos-api.gitlab.io/picos/changelog.html#id20), `picos` added the `Valuable` class that is now interfering with the reshaping. For the time being, I changed the readme to reflect that one must use a version of PICOS not higher than 2.2. You can install this version either by running the command `conda install -c picos picos==2.2` if you use Anaconda, or `pip install picos==2.2`. I will look into modifying the code so that it works with newer versions of PICOS.

**Comment by jianhui1998** [comment]
Thanks for your efficient response to resolve this issue, and I'll be following your modification, so I closed this issue
